/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cpp3DPathPlanning_Cpp_3DPathPlanning */

#ifndef _Included_cpp3DPathPlanning_Cpp_3DPathPlanning
#define _Included_cpp3DPathPlanning_Cpp_3DPathPlanning
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cpp3DPathPlanning_Cpp_3DPathPlanning
 * Method:    MapUpdate
 * Signature: ([DDIDD)I
 */
JNIEXPORT jint JNICALL Java_cpp3DPathPlanning_Cpp_13DPathPlanning_MapUpdate
  (JNIEnv *, jclass, jdoubleArray, jdouble, jint, jdouble, jdouble);

/*
 * Class:     cpp3DPathPlanning_Cpp_3DPathPlanning
 * Method:    mapSetOb
 * Signature: ([D[D)I
 */
JNIEXPORT jint JNICALL Java_cpp3DPathPlanning_Cpp_13DPathPlanning_mapSetOb
  (JNIEnv *, jclass, jdoubleArray, jdoubleArray);

/*
 * Class:     cpp3DPathPlanning_Cpp_3DPathPlanning
 * Method:    setRobAbi
 * Signature: ([D)I
 */
JNIEXPORT jint JNICALL Java_cpp3DPathPlanning_Cpp_13DPathPlanning_setRobAbi
  (JNIEnv *, jclass, jdoubleArray);

/*
 * Class:     cpp3DPathPlanning_Cpp_3DPathPlanning
 * Method:    MotionPlanning
 * Signature: (DDDDI)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_cpp3DPathPlanning_Cpp_13DPathPlanning_MotionPlanning
  (JNIEnv *, jclass, jdouble, jdouble, jdouble, jdouble, jint);

#ifdef __cplusplus
}
#endif
#endif
